

Linear Algebra Practicals

1.Solving the system of linear equations using Cramer’s rule.

In [2]:
import numpy as np
A=np.array([[11,16,10,6],[4,3,2,2],[4,5,3,2],[2,3,2,1]])
A

array([[11, 16, 10,  6],
       [ 4,  3,  2,  2],
       [ 4,  5,  3,  2],
       [ 2,  3,  2,  1]])

In [3]:
B=np.array([84,18,26,16])
row,col=A.shape
x=[0]*col
for i in range(col):
    temp=A.copy()
    temp[:,i]=B
    x[i]=np.linalg.det(temp)/np.linalg.det(A)
np.round(x)

array([-0.,  2.,  4.,  2.])

In [4]:
x=np.linalg.solve(A,B)
np.round(x)

array([-0.,  2.,  4.,  2.])

2..Pseudo Inverse of Matrix

In [5]:
A=np.array([[3,5,2,-4,-6],[1,2,-4,-6,7],[8,3,10,-6,-25]])
A
b=np.array([34,-45,129])
b
B=np.linalg.pinv(A)
B

array([[-0.04014096,  0.05331913,  0.03135552],
       [ 0.3       , -0.1       , -0.1       ],
       [ 0.01186691, -0.03291264,  0.00216358],
       [ 0.09214883, -0.13955089, -0.06054745],
       [ 0.00578594,  0.02538928, -0.02656941]])

In [6]:
np.allclose(A, np.dot(A, np.dot(B, A)))
np.allclose(B, np.dot(B, np.dot(A, B)))

True

3.Checking various properties of the given matrix.

    Square Matrix

In [9]:
A=np.array([[11,16,10,6],[4,3,2,2],[4,5,3,2],[2,3,2,1]])
m,n=A.shape
if m==n:
    print('Matrix is square')
else:
    print('Matrix is not square')     

Matrix is square




    Idempotent Matrix



In [10]:
A2=np.linalg.matrix_power(A,2)
if (A==A2).all():
    print('Matrix is idempotent')
else:
     print('Matrix is not idempotent')

Matrix is not idempotent


Symmetric Matrix

In [11]:
B=np.array([[1,1,3],[1,3,1],[3,1,1]])
if (B==B.T).all():
    print('Matrix is Symmetric')
else:
     print('Matrix is not Symmetric')

Matrix is Symmetric




    Orthogonality of the Matrix



In [12]:
C=np.array([[1,1,3],[1,3,1],[3,1,1]])
if np.linalg.det(C)!=0:
    if(np.linalg.inv(C)==C.T).all():
        print('Matrix is Orthogonal')
    else:
         print('Matrix is  not Orthogonal')

Matrix is  not Orthogonal


Skew Symmetric Matrix

In [13]:
D=np.array([[0,1,-2],[-1,0,3],[2,-3,0]])
if (D.T==-D).all():
    print('Matrix is Skew Symmetric')
else:
     print('Matrix is not Skew Symmetric')

Matrix is Skew Symmetric




    Definiteness



In [14]:
A=np.array([[3,2,4],[2,0,2],[4,2,3]])
Ev=np.linalg.eigvals(A)
if np.all(Ev>0):
    print('Positive Definite')
elif np.all(Ev>=0):
    print('Positive Semi Definite')  
elif np.all(Ev<0):
    print('Negative Definite')  
elif np.all(Ev<=0):
    print('Negative Semi Definite') 
else:
    print('Indefinite')
    

Indefinite




4.Generalized Inverse


In [15]:
A=np.array([[2.5,0.58,0.4],[0.6,0.32,1],[0.2,0.84,4]])
A
r=np.linalg.matrix_rank(A)
r
m,n=A.shape
G=np.zeros([3,3])
B=A[0:r,0:r]
G2= G[0:r,0:r]
H=np.linalg.inv(B)
G[0:r,0:r]=H
G

array([[ 0.7079646 , -1.28318584,  0.        ],
       [-1.32743363,  5.53097345,  0.        ],
       [ 0.        ,  0.        ,  0.        ]])

5.Checking linear dependence/ independence of set of vectors

In [16]:
u = np.array([1, 0, 1])
v = np.array([1, 1, 0])
w = np.array([1, 2, 1])
print('Does the equality w = 2v-u  holds? Answer:', np.all(w == 2*v-u ))
#  Here vectors are independent.

Does the equality w = 2v-u  holds? Answer: False


6.Grams-Schmdit Orthogonalisation

In [17]:
A = np.array([[1.0, 1.0, 0.0], [1.0, 3.0, 1.0], [2.0, -1.0, 1.0]])
A
def gram_schmidt(A):
    """Orthogonalize a set of vectors stored as the columns of matrix A."""
    n = A.shape[1]
    for j in range(n):
        for k in range(j):
            A[:, j] -= np.dot(A[:, k], A[:, j]) * A[:, k]
        A[:, j] = A[:, j] / np.linalg.norm(A[:, j])
    return A

if __name__ == '__main__':
    print(gram_schmidt(A))

[[ 0.40824829  0.20739034 -0.88900089]
 [ 0.40824829  0.82956136  0.38100038]
 [ 0.81649658 -0.51847585  0.25400025]]
